import React from 'react'
import beckgroungTransperant from '../../beckgroungTransperant.png'
import ServerFlow3 from "./ServerFlow3.png"
import Results3 from "./Results3.png"
import ServerFlow2 from "./ServerFlow2.png"
import Results2 from "./Results2.png"

export default function WelcomePanel() {
    return (
        <div style={{backgroundImage: `url(${beckgroungTransperant})`}}>
            <h1><span style={{color: '#0FA6AB'}}>Welcome to CytoMod</span></h1>
            <p style={{fontSize: 20}} className="pt-running-text">
            CytoMod is a computational method for analysis of cytokine profiles based on identifying sets of co-signaling cytokines (<a href="https://www.frontiersin.org/articles/10.3389/fimmu.2019.01338/">Cohen et al., 2019</a>, 
            <a href="https://www.frontiersin.org/articles/10.3389/fimmu.2017.01423/full"> Fiore-Gartland et al., 2017</a>)
            </p> 
            <p style={{fontSize: 20}} className="pt-running-text">
            CytoMod uses a data driven approach for grouping cytokines into modules - sets of co-signaling cytokines. Such modules may provide insights 
            into the cytokine signaling network underlying a specific immune context, and also allow to increase the statistical power to detect associations
            between cytokine levels and clinical phenotypes.
            </p> 
            <p style={{fontSize: 20}} className="pt-running-text">
            This server allows running CytoMod on your cytokine profile dataset of choice. 
            CytoMod can be applied to any cytokine dataset, and only requires the cytokines measurements and optionally some clinical outcomes.
            The data can be provided either directly as Luminex output files, or as an excel file (see example formats in the "Example" tab on the left bar).   
            Uploaded data and result files are saved for 7 days, after which they are deleted from the server. 
            </p>
            <h3 >To run the method click on the Run tab above and follow instructions within. The results tab can allow you to retrieve your results, which will be stored on the server for 7 days. To follow an example, please click on the "Example" tab, found on the left bar </h3>
            <p>  </p>
            <h2>Main server workflow:</h2>
            <a download = {'CytoMod server flow.png'} href= {ServerFlow2} title={'CytoMod server flow'} >
            <img src={ServerFlow3} alt="The server flow" class="center" /></a>;
            <p style={{fontSize: 14}} className="pt-running-text" class='center'>The application operates as a three steps pipeline: (1) The user uploads his data using two files - a cytokines measurements file and an optional clinical measurements outcome file; (2) The user specifies the cytokines and outcomes he wishes to analyze, and can also tune the default statistical parameters, such as the number of clusters - K, log transformation of the raw data and covariates variables; and (3) The method is run and the user can view and download the results. Results are stored for one week from submission and can be accessed using a unique ID provided at runtime. This allows the user to access his results, without needing to re-run the analysis. The results and data cannot be accessed by other users. In addition, the method can be executed without any outcome variables.</p>
            <p style={{fontSize: 20}} className="pt-running-text">After generating the method, results tab will present several sections:</p>
            <a download = {'CytoMod results demo.png'} href= {Results2} title={'CytoMod results demo'} >
            <img src={Results3} alt="Results tabs" class="center"/></a>;
            <p style={{fontSize: 14}} className="pt-running-text" class='center'>Figures generated by the Cytomod server: (Left) Clustering tab. Clustering cytokines into modules. Top:  The pairwise correlation matrix between cytokines, with the  clustering dendrogram generated. Cytokine modules are presented as different colors on the y-axis color bar. Bottom: Pairwise reliability scores generated based on data bootstrapping . (Center) Module inner-correlations tab -  Pairwise correlations between all cytokines within each cytokine module (module M1 from the left panel depicted here). (Right) Outcome associations tab. Associations between cytokine modules and individual cytokines with clinical phenotypes (optional). Heatmap colors indicate the direction and magnitude of the regression coefficient. Only associations with false-discovery rate (FDR)-adjusted q-value ≤ 0.2 are colored. Asterisks indicate family-wise error rate (FWER)-adjusted p-values with ***, **, and * indicating p ≤ 0.0005, 0.005, and 0.05, respectively. The user can specify analysis hyper parameters (such as the number of clusters, or log-transformation of data).
</p>
            <p style={{fontSize: 20}} className="pt-running-text">Results will also be available for download.</p>

            <p style={{fontSize: 20}} className="pt-running-text">The method's code holds the  <a href="https://github.com/liel-cohen/CytoMod/blob/master/LICENSE">MIT License</a></p>


           {/* <p style={{color: '#0B7478', fontSize: 22}}>This server was published on XXX - see the paper <a href="">here</a></p> */}
        </div>
    )
}






